services:
  postgres:
    build: .
    container_name: postgres_interview_lab
    environment:
      POSTGRES_DB: interview_lab
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
